name: "Build NX Packages"
on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches:
      - master
permissions:
  contents: write

jobs:
  buildNXPkgs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v24
        with:
          nix_conf: |
            build-users-group =
            experimental-features = nix-command flakes

      - name: Install Requred Packages
        run:
          # nix-env -iA jq python39 -f https://github.com/NixOS/nixpkgs/archive/refs/tags/23.05.tar.gz
          nix-env -iA python39 jq -f https://github.com/tywtyw2002/nx-direct/tarball/nx

      - name: Follow cFlake Version
        run: |
          nix flake metadata . --json | jq ".locks.nodes.nixpkgs.locked.rev" -r > nx_hash
          git rev-parse --short HEAD >> nx_hash

      - name: Check Flake Version
        id: check_version
        run: |
          curl -sL https://raw.githubusercontent.com/tywtyw2002/nx-direct/nx/nx_hash > release_hash
          hashDiff=$(diff release_hash nx_hash &>/dev/null || echo "YES")
          echo "NEED_BUILD=$hashDiff" >> $GITHUB_OUTPUT

      - name: Build Pkgs
        if: ${{ steps.check_version.outputs.NEED_BUILD }}
        run: |
          nix eval .#nx-direct-builder | jq "fromjson" > result
          python3 gen_nx.py
          cp nx_hash ./out/

      - name: Push to nx
        uses: JamesIves/github-pages-deploy-action@v4
        if: ${{ steps.check_version.outputs.NEED_BUILD }}
        with:
          folder: out
          branch: nx
          clean: true
          single-commit: true

